### ISSUE TITLE
Missing dependency LcDialog / LcTemplates

### ISSUE THREAD

**Issue by pettaa123** [opengds/DesignPatterns#1]
I opened the State 1 pattern with LV2023. I have missing dependencies for LcDialog and LcTemplates.

**Comment by MikaelHolmstrom** [comment]
Oops that is not good, let me fix that

**Comment by MikaelHolmstrom** [comment]
I've pushed some cleanup

**Comment by MikaelHolmstrom** [comment]
Try now

**Comment by pettaa123** [comment]
Awesome project and issue is fixed
